import { StyleSheet } from 'react-native';

// Main app styles
export const homeStyles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: "white",
  },
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#F0F8FF',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#F0F8FF',
  },
  backButtonText: {
    marginLeft: 6,
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
  },
  navigationBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#FAFAFA',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  contentContainer: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
  },
  loadingContainer: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 8,
  },
  navButtonText: {
    marginHorizontal: 6,
    fontSize: 14,
    color: '#333',
  },
  surahInfoContainer: {
    alignItems: 'center',
    flex: 1,
    paddingRight: 8,
  },
  currentSurahText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  paginationText: {
    fontSize: 12,
    color: '#666',
    marginTop: 4,
  },
  screenTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  settingsButton: {
    padding: 8,
  },
  flatListContent: {
    padding: 16,
  },
  ayahContainer: {
    backgroundColor: '#F0F8FF',
    padding: 16,
    marginBottom: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    elevation: 2,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    paddingBottom: 8,
  },
  headerText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  surahName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'right',
  },
  contentRow: {
    marginBottom: 12,
  },
  ayahBox: {
    marginBottom: 8,
  },
  arabicText: {
    fontSize: 22,
    textAlign: 'right',
    fontWeight: '600',
    color: '#000',
    marginBottom: 4,
  },
  ayahNumber: {
    fontSize: 14,
    color: '#666',
    textAlign: 'right',
  },
  translationBox: {
    marginBottom: 8,
  },
  translationText: {
    fontSize: 16,
    color: '#333',
    lineHeight: 24,
  },
  tafseerBox: {
    backgroundColor: '#F8F8F8',
    padding: 12,
    borderRadius: 6,
  },
  tafseerLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 4,
  },
  tafseerText: {
    fontSize: 14,
    color: '#666',
    lineHeight: 20,
  },
  noDataContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  noDataText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#666',
    textAlign: 'center',
  },
  pageNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#F0F8FF',
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  pageNavButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    minWidth: 120,
    justifyContent: 'center',
  },
  pageNavButtonAlt: {
    backgroundColor: '#F0F8FF',
    borderColor: '#81b0ff',
  },
  pageNavText: {
    marginHorizontal: 6,
    fontSize: 14,
    color: '#333',
    textAlign: 'center',
  },
  pageIndicator: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#333',
  },
  errorText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#666',
    textAlign: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  // Toast notification styles for the last read feature
  toastContainer: {
    position: 'absolute',
    top: 60,
    left: 20,
    right: 20,
    backgroundColor: 'rgba(0, 128, 128, 0.9)',
    borderRadius: 8,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  toastText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 8,
  },
  toastIcon: {
    marginRight: 6,
  },
  pageIndicatorHeader: {
    flex: 1,
    alignItems: 'flex-end',
  },
  paginationTextHeader: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
  },
}); 